const PDFDocument = require("pdfkit");

exports.generatePDF = (report) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        size: "A4",
      });

      const chunks = [];

      // Collect PDF data in memory
      doc.on("data", (chunk) => {
        chunks.push(chunk);
      });

      doc.on("end", () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      });

      doc.on("error", (error) => {
        reject(error);
      });

      // =========================================================
      // TITLE
      // =========================================================

      doc
        .fontSize(22)
        .text("Expense Tracker Report", {
          align: "center",
        });

      doc.moveDown();

      doc
        .fontSize(10)
        .text(`Generated on: ${new Date().toLocaleDateString()}`, {
          align: "center",
        });

      doc.moveDown(2);

      // =========================================================
      // SUMMARY
      // =========================================================

      doc.fontSize(16).text("Summary");

      doc.moveDown();

      doc
        .fontSize(12)
        .text(
          `Total Income: ₹${Number(
            report.totalIncome || 0
          ).toFixed(2)}`
        );

      doc
        .text(
          `Total Expense: ₹${Number(
            report.totalExpense || 0
          ).toFixed(2)}`
        );

      doc
        .text(
          `Balance: ₹${Number(
            report.balance || 0
          ).toFixed(2)}`
        );

      doc.moveDown(2);

      // =========================================================
      // CATEGORY BREAKDOWN
      // =========================================================

      doc.fontSize(16).text("Category Breakdown");

      doc.moveDown();

      if (
        Array.isArray(report.categoryBreakdown) &&
        report.categoryBreakdown.length > 0
      ) {
        report.categoryBreakdown.forEach((item) => {
          const category =
            item.category ||
            item.name ||
            "Unknown";

          const amount =
            item.amount ||
            item.total ||
            0;

          doc
            .fontSize(11)
            .text(
              `${category}: ₹${Number(amount).toFixed(2)}`
            );
        });
      } else {
        doc
          .fontSize(11)
          .text("No category data available.");
      }

      doc.moveDown(2);

      // =========================================================
      // TOP EXPENSES
      // =========================================================

      doc.fontSize(16).text("Top Expenses");

      doc.moveDown();

      if (
        Array.isArray(report.topExpenses) &&
        report.topExpenses.length > 0
      ) {
        report.topExpenses.forEach((item, index) => {
          const description =
            item.description ||
            item.title ||
            "Expense";

          const category =
            item.category ||
            item.categoryName ||
            "N/A";

          const amount =
            item.amount ||
            0;

          const date =
            item.date ||
            item.created_at ||
            "";

          doc
            .fontSize(11)
            .text(
              `${index + 1}. ${description}`
            );

          doc
            .fontSize(10)
            .text(
              `   Category: ${category}`
            );

          doc
            .fontSize(10)
            .text(
              `   Amount: ₹${Number(amount).toFixed(2)}`
            );

          if (date) {
            doc
              .fontSize(10)
              .text(`   Date: ${date}`);
          }

          doc.moveDown(0.7);
        });
      } else {
        doc
          .fontSize(11)
          .text("No expense data available.");
      }

      // =========================================================
      // FOOTER
      // =========================================================

      doc.moveDown(2);

      doc
        .fontSize(9)
        .text(
          "Generated by Expense Tracker",
          {
            align: "center",
          }
        );

      // Finish PDF
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};