const PDFDocument = require("pdfkit");
const fs = require("fs-extra");
const path = require("path");


async function generateExpenseReport(report) {

  return new Promise(async (resolve, reject) => {

    try {

      /* =====================================================
         OUTPUT
      ===================================================== */

      const folder = path.join(

        __dirname,

        "../temp/reports"

      );

      await fs.ensureDir(folder);

      const fileName =

        `Expense_Report_${Date.now()}.pdf`;

      const filePath = path.join(

        folder,

        fileName

      );

      /* =====================================================
         PDF
      ===================================================== */

      const doc = new PDFDocument({

        size: "A4",

        margin: 40,

        bufferPages: true

      });

      const stream = fs.createWriteStream(filePath);

      doc.pipe(stream);

      /* =====================================================
         COLORS
      ===================================================== */

      const PRIMARY = "#2563EB";

      const SUCCESS = "#22C55E";

      const DANGER = "#EF4444";

      const DARK = "#111827";

      const GRAY = "#6B7280";

      const CARD = "#F8FAFC";

      /* =====================================================
         HEADER
      ===================================================== */

      function drawHeader() {

        doc

          .rect(0, 0, 595, 70)

          .fill(PRIMARY);

        doc

          .fillColor("white")

          .fontSize(24)

          .font("Helvetica-Bold")

          .text(

            "Expense Tracker Report",

            40,

            22

          );

      }

      /* =====================================================
         FOOTER
      ===================================================== */

      function drawFooter() {

        const page =

          doc.bufferedPageRange();

        for (

          let i = page.start;

          i < page.start + page.count;

          i++

        ) {

          doc.switchToPage(i);

          doc

            .fontSize(10)

            .fillColor(GRAY)

            .text(

              `Generated by Expense Tracker | Page ${i + 1}`,

              40,

              810,

              {

                align: "center"

              }

            );

        }

      }

      /* =====================================================
         SUMMARY CARD
      ===================================================== */

      function summaryCard(

        x,

        y,

        title,

        value,

        color

      ) {

        doc

          .roundedRect(

            x,

            y,

            120,

            70,

            8

          )

          .fillAndStroke(

            CARD,

            "#E5E7EB"

          );

        doc

          .fillColor(GRAY)

          .fontSize(11)

          .font("Helvetica")

          .text(

            title,

            x + 12,

            y + 10

          );

        doc

          .fillColor(color)

          .fontSize(18)

          .font("Helvetica-Bold")

          .text(

            `₹${Number(value).toLocaleString()}`,

            x + 12,

            y + 35

          );

      }

      /* =====================================================
         PAGE 1
      ===================================================== */

      drawHeader();

      doc.moveDown(4);

      doc

        .fillColor(DARK)

        .fontSize(14)

        .font("Helvetica-Bold")

        .text(

          "Financial Summary",

          40,

          90

        );

      doc

        .fontSize(11)

        .fillColor(GRAY)

        .font("Helvetica")

        .text(

          `Generated : ${new Date().toLocaleString()}`,

          40,

          115

        );

      /* =====================================================
         SUMMARY
      ===================================================== */

      summaryCard(

        40,

        160,

        "Income",

        report.summary.income,

        SUCCESS

      );

      summaryCard(

        180,

        160,

        "Expense",

        report.summary.expense,

        DANGER

      );

      summaryCard(

        320,

        160,

        "Balance",

        report.summary.balance,

        PRIMARY

      );

      summaryCard(

        460,

        160,

        "Savings",

        report.monthlySavings.savings,

        "#9333EA"

      );

      /* =====================================================
         INTRODUCTION
      ===================================================== */

      doc

        .fillColor(DARK)

        .fontSize(14)

        .font("Helvetica-Bold")

        .text(

          "Overview",

          40,

          270

        );

      doc

        .fontSize(11)

        .fillColor(GRAY)

        .font("Helvetica")

        .text(

          "This report provides a complete overview of your financial activities including income, expenses, budget performance, account balances, payment methods and transaction history. The following pages contain graphical analysis and detailed transaction reports.",

          {

            width: 500,

            align: "justify"

          }

        );

      /* =====================================================
         NEXT PAGE
      ===================================================== */

      doc.addPage();

      /* =====================================================
         FOOTER
      ===================================================== */

      drawFooter();

      /* =====================================================
         FINISH
      ===================================================== */

      doc.end();

      stream.on("finish", () => {

        resolve(filePath);

      });

      stream.on("error", reject);

    }

    catch (err) {

      reject(err);

    }

  });

}


module.exports = {

  generateExpenseReport

};

      /* =====================================================
         CHARTS
      ===================================================== */

      const {

        generateExpensePieChart,

        generateMonthlyBarChart,

        generatePaymentChart

      } = require("../helpers/chart.helper");

      /* =====================================================
         GENERATE CHARTS
      ===================================================== */

      const pieChart =

        await generateExpensePieChart(

          report.expenseByCategory

        );

      const barChart =

        await generateMonthlyBarChart(

          report.monthlySummary

        );

      const paymentChart =

        await generatePaymentChart(

          report.paymentMethods

        );

      /* =====================================================
         PAGE 2
      ===================================================== */

      drawHeader();

      doc

        .fillColor(DARK)

        .fontSize(18)

        .font("Helvetica-Bold")

        .text(

          "Expense By Category",

          40,

          90

        );

      doc

        .fontSize(11)

        .fillColor(GRAY)

        .text(

          "Distribution of expenses across all categories.",

          40,

          115

        );

      doc.image(

        pieChart,

        70,

        150,

        {

          width: 450,

          align: "center"

        }

      );

      doc.addPage();

      /* =====================================================
         PAGE 3
      ===================================================== */

      drawHeader();

      doc

        .fillColor(DARK)

        .fontSize(18)

        .font("Helvetica-Bold")

        .text(

          "Monthly Income vs Expense",

          40,

          90

        );

      doc

        .fontSize(11)

        .fillColor(GRAY)

        .text(

          "Comparison of monthly income and expenses.",

          40,

          115

        );

      doc.image(

        barChart,

        30,

        150,

        {

          width: 520

        }

      );

      doc.addPage();

      /* =====================================================
         PAGE 4
      ===================================================== */

      drawHeader();

      doc

        .fillColor(DARK)

        .fontSize(18)

        .font("Helvetica-Bold")

        .text(

          "Payment Methods",

          40,

          90

        );

      doc

        .fontSize(11)

        .fillColor(GRAY)

        .text(

          "Transactions grouped by payment method.",

          40,

          115

        );

      doc.image(

        paymentChart,

        70,

        150,

        {

          width: 450

        }

      );

      doc.addPage();

            /* =====================================================
         PAGE 5
      ===================================================== */

      drawHeader();

      doc

        .fillColor(DARK)

        .fontSize(20)

        .font("Helvetica-Bold")

        .text(

          "Budget & Account Overview",

          40,

          90

        );

      /* =====================================================
         BUDGET CARD
      ===================================================== */

      const budget = report.budget;

      doc

        .roundedRect(

          40,

          130,

          510,

          120,

          8

        )

        .fillAndStroke(

          "#F8FAFC",

          "#E5E7EB"

        );

      doc

        .fillColor(PRIMARY)

        .fontSize(16)

        .font("Helvetica-Bold")

        .text(

          "Budget Summary",

          60,

          150

        );

      doc

        .fillColor(DARK)

        .fontSize(11)

        .font("Helvetica")

        .text(

          `Total Budget : ₹${Number(budget.totalBudget).toLocaleString()}`,

          60,

          180

        )

        .text(

          `Spent : ₹${Number(budget.spent).toLocaleString()}`,

          60,

          200

        )

        .text(

          `Remaining : ₹${Number(budget.remaining).toLocaleString()}`,

          260,

          180

        )

        .text(

          `Status : ${budget.status}`,

          260,

          200

        );

      /* =====================================================
         PROGRESS BAR
      ===================================================== */

      const progressWidth = 420;

      const usage = Math.min(

        budget.usage,

        100

      );

      doc

        .roundedRect(

          60,

          225,

          progressWidth,

          16,

          8

        )

        .fill("#E5E7EB");

      let progressColor = SUCCESS;

      if (

        budget.status === "Warning"

      )

        progressColor = "#F59E0B";

      if (

        budget.status === "Over Budget"

      )

        progressColor = DANGER;

      doc

        .roundedRect(

          60,

          225,

          progressWidth * usage / 100,

          16,

          8

        )

        .fill(progressColor);

      doc

        .fillColor(DARK)

        .fontSize(10)

        .text(

          `${usage}% Used`,

          490,

          223

        );

      /* =====================================================
         ACCOUNT SUMMARY
      ===================================================== */

      doc

        .fillColor(PRIMARY)

        .fontSize(16)

        .font("Helvetica-Bold")

        .text(

          "Accounts",

          40,

          280

        );

      let accountY = 315;

      report.accounts.forEach(

        (account) => {

          doc

            .roundedRect(

              40,

              accountY,

              510,

              34,

              5

            )

            .fillAndStroke(

              "#FFFFFF",

              "#E5E7EB"

            );

          doc

            .fillColor(DARK)

            .fontSize(11)

            .font("Helvetica-Bold")

            .text(

              account.name,

              55,

              accountY + 10

            );

          doc

            .font("Helvetica")

            .text(

              account.type,

              220,

              accountY + 10

            );

          doc

            .fillColor(SUCCESS)

            .text(

              `₹${Number(

                account.current_balance

              ).toLocaleString()}`,

              430,

              accountY + 10

            );

          accountY += 42;

        }

      );

      /* =====================================================
         STATISTICS
      ===================================================== */

      doc

        .fillColor(PRIMARY)

        .fontSize(16)

        .font("Helvetica-Bold")

        .text(

          "Statistics",

          40,

          accountY + 15

        );

      const stats = report.statistics;

      const statsY = accountY + 45;

      summaryCard(

        40,

        statsY,

        "Transactions",

        stats.totalTransactions,

        PRIMARY

      );

      summaryCard(

        180,

        statsY,

        "Income",

        stats.incomeTransactions,

        SUCCESS

      );

      summaryCard(

        320,

        statsY,

        "Expense",

        stats.expenseTransactions,

        DANGER

      );

      summaryCard(

        460,

        statsY,

        "Accounts",

        stats.totalAccounts,

        "#9333EA"

      );

      doc.addPage();

            /* =====================================================
         PAGE 6
      ===================================================== */

      drawHeader();

      doc
        .fillColor(DARK)
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("Transaction Details", 40, 90);

      /* =====================================================
         TABLE HEADER
      ===================================================== */

      const startY = 130;

      const rowHeight = 28;

      doc
        .rect(40, startY, 515, rowHeight)
        .fill(PRIMARY);

      doc
        .fillColor("white")
        .fontSize(10)
        .font("Helvetica-Bold");

      doc.text("Date", 48, startY + 8);

      doc.text("Title", 110, startY + 8);

      doc.text("Category", 230, startY + 8);

      doc.text("Account", 330, startY + 8);

      doc.text("Amount", 425, startY + 8);

      doc.text("Type", 505, startY + 8);

      /* =====================================================
         TABLE ROWS
      ===================================================== */

      let rowY = startY + rowHeight;

      const rows = report.transactions;

      rows.forEach((item, index) => {

        if (rowY > 730) {

          doc.addPage();

          drawHeader();

          rowY = 90;

        }

        if (index % 2 === 0) {

          doc

            .rect(40, rowY, 515, rowHeight)

            .fill("#F8FAFC");

        }

        doc

          .fillColor(DARK)

          .font("Helvetica")

          .fontSize(9);

        doc.text(

          new Date(item.transaction_date)

            .toLocaleDateString(),

          48,

          rowY + 8,

          {

            width: 55

          }

        );

        doc.text(

          item.title,

          110,

          rowY + 8,

          {

            width: 110

          }

        );

        doc.text(

          item.category,

          230,

          rowY + 8,

          {

            width: 90

          }

        );

        doc.text(

          item.account,

          330,

          rowY + 8,

          {

            width: 80

          }

        );

        doc

          .fillColor(

            item.type === "income"

              ? SUCCESS

              : DANGER

          )

          .font("Helvetica-Bold")

          .text(

            `₹${Number(

              item.amount

            ).toLocaleString()}`,

            425,

            rowY + 8,

            {

              width: 70,

              align: "right"

            }

          );

        doc

          .fillColor(DARK)

          .font("Helvetica")

          .text(

            item.type,

            505,

            rowY + 8

          );

        rowY += rowHeight;

      });

      /* =====================================================
         LAST PAGE
      ===================================================== */

      doc.addPage();

      drawHeader();

      doc

        .fillColor(DARK)

        .fontSize(22)

        .font("Helvetica-Bold")

        .text(

          "Report Summary",

          40,

          90

        );

      doc

        .fontSize(12)

        .font("Helvetica")

        .fillColor(GRAY)

        .text(

          "This report was automatically generated by the Expense Tracker System.",

          40,

          130,

          {

            width: 500,

            align: "justify"

          }

        );

      doc.moveDown();

      doc

        .fillColor(PRIMARY)

        .fontSize(16)

        .font("Helvetica-Bold")

        .text(

          "Highlights",

          40,

          190

        );

      const highlights = [

        `Total Income : ₹${Number(report.summary.income).toLocaleString()}`,

        `Total Expense : ₹${Number(report.summary.expense).toLocaleString()}`,

        `Net Balance : ₹${Number(report.summary.balance).toLocaleString()}`,

        `Budget Status : ${report.budget.status}`,

        `Accounts : ${report.accounts.length}`,

        `Transactions : ${report.statistics.totalTransactions}`

      ];

      let pointY = 225;

      highlights.forEach((text) => {

        doc

          .circle(

            48,

            pointY + 6,

            2

          )

          .fill(PRIMARY);

        doc

          .fillColor(DARK)

          .fontSize(11)

          .text(

            text,

            60,

            pointY

          );

        pointY += 28;

      });

      doc

        .moveTo(

          40,

          450

        )

        .lineTo(

          555,

          450

        )

        .strokeColor("#D1D5DB")

        .stroke();

      doc

        .fillColor(GRAY)

        .fontSize(11)

        .text(

          "Generated on : " +

          new Date().toLocaleString(),

          40,

          470

        );

      doc

        .fontSize(13)

        .fillColor(PRIMARY)

        .font("Helvetica-Bold")

        .text(

          "Thank you for using Expense Tracker",

          40,

          520,

          {

            align: "center"

          }

        );

      /* =====================================================
         FOOTERS
      ===================================================== */

      drawFooter();